[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin-solidity=node_modules/openzeppelin-solidity",
    "canonical-weth=node_modules/canonical-weth",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
