[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin-solidity=node_modules/openzeppelin-solidity",
    "canonical-weth=node_modules/canonical-weth",
]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = false
multiline_func_header = "all"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
